baseURL = "http://www.valentincauro.com/"
title = "Valentin Cauro — Designer Graphique Multimedia"
theme = "Keauval0.1"
description = "Valentin Cauro - Designer graphique multimedia"

[taxonomies]
category = "categories"