baseURL = "http://www.valentincauro.com/"
description = "Valentin Cauro - Designer graphique multimedia"
theme = "Keauval0.1"
title = "Valentin Cauro — Designer Graphique Multimedia"
[taxonomies]
category = "categories"
